### ISSUE TITLE
Uber opens Safari when i click on uberButton

### ISSUE THREAD

**Issue by alvinvarghese** [uber/rides-ios-sdk#15]
I have not installed uber in my iPhone, so uber is opening  a URL in Safari. It is okay, Safari says could not load URL. Why ??

Really i don't wanna open Safari if it is not opening a proper page. I don't wanna create a bad user experience. 

Would you give a chance for developers to decide choose way to open the URL ? via Uber app or via Safari.

**Comment by faarwa** [comment]
Hi Alvin, are you testing your app on simulator or on device? The SDK checks whether the uber app is installed, and if it isn't, directs the user to the app store. If you're testing on simulator, the link seems to be failing because there is no App Store on simulator. If you're testing on device and the link is failing, please provide some more information on your set up and I'd be glad to assist you through the problem.

**Comment by alvinvarghese** [comment]
I am testing in a Physical Device. And when i click on uber button it directly opens URL in Safari, And Safari says could not load URL ?? Why?

**Comment by faarwa** [comment]
Please provide more information such as your iPhone model and iOS version. It would also be a useful test to run our example app on your phone and see if the same behavior is occurring.

**Comment by alvinvarghese** [comment]
We have tested it in iPhone 5C and iPhone 6, iPhone 6S. All devices are running in latest iOS 9.2.

 If the uber app is not installed in device, UberButton opens Safari, and shows a message could not open the page.

**Comment by faarwa** [comment]
To be clear, is this behavior also occurring when you run our example app in the repo on your device? 

I understand what problem you're encountering, but I'm asking follow-up questions so that I can reproduce it myself, as I am not yet able to see the same problem you're seeing (I'm running iOS 9.2 on iPhone 6 as well).

**Comment by alvinvarghese** [comment]
Downloading... And checking... give me a sec.

**Comment by faarwa** [comment]
Thanks! I'm testing out some different conditions on my side as well.

**Comment by faarwa** [comment]
What country is your app store set to?

**Comment by alvinvarghese** [comment]
India, Just downloaded the example and all of a sudden it showed "No such module UberRides". Looks like i have to manually install it.

**Comment by faarwa** [comment]
The example apps are set up to be integrated via Cocoapods `pod install`, which create the `.xcworkspace` project.

**Comment by alvinvarghese** [comment]
This is the code.

```
    /**
     Execute deeplink to launch the Uber app. Redirect to the app store if the app is not installed.
     */
    public func execute() {
        let deeplinkURL = createURL(deeplinkURI!)
        let appstoreURL = createURL("https://m.uber.com/sign-up?client_id=" + clientID)

        if UIApplication.sharedApplication().canOpenURL(deeplinkURL) {
            UIApplication.sharedApplication().openURL(deeplinkURL)
            
        } else {
            UIApplication.sharedApplication().openURL(appstoreURL)
        }
```

**Comment by faarwa** [comment]
When you run the example app on your phone and click one of the request buttons (need to replace the client ID placeholder string in `AppDelegate`), does the same behavior occur where Safari fails to load the URL?

Yup, that code checks whether Uber is installed on your phone, and if it isn't, directs to the `m.uber` link which *should* be redirecting to the App Store. It seems it's the redirect thats failing for you, so I'm trying to figure out what might be causing that.

**Comment by faarwa** [comment]
This is what shows up when I visit that link on iPhone Safari for the first time:
![image](https://cloud.githubusercontent.com/assets/2192960/13736674/dde0fa34-e973-11e5-89c7-0b599d99eb1b.png)
If I click Open, it goes to App Store for every visit to the link after. If I click Cancel, it will fail to open the URL for every visit to the link after. 

If you delete your Safari History and Website Settings from System Preferences and visit the link again, do you see this dialog?

**Comment by alvinvarghese** [comment]
Yes. Finally you figured it out for me. Thanks a lot. This is the problem. I clicked on "Cancel", which led into this problem. 

Thanks for your valuable time, You can close this issue now.

**Comment by faarwa** [comment]
Awesome, glad we figured this out!

**Comment by maysken** [comment]
Hi I am seeing this same issue on Safari for iPhone, except I am not sure what helped the op fix the issue they were having.  I have tried clearing the Safari history in settings, however I still get prompted to go to the App Store to download Uber even though it is already installed.  If I click cancel, I have a page that has an Open In Uber button.  Clicking the Open In Uber button opens Uber, but does not use the deep link info from the original link that got you there in the first place.  This was working a few days back, but I'm unsure what changed possibly with the phone/Safari/Uber app(?) that could have caused it to start doing this?  Nothing has changed with the page that contains the deeplink at all since well before it stopped working.  Additionally, I am only seeing this issue on one of my test phones which is an iPhone 5s with latest iOS and latest Uber app installed.

Thank you,
Ken

**Comment by jbrophy17** [comment]
It seems like the op got into this situation when they chose 'cancel' when attempting to open a deeplink. I think you might be able to get back to the original behavior if you scroll up on the safari page that is opened after following the deeplink & tap on the banner that says 'open in uber'

**Comment by maysken** [comment]
Hi jbrophy17,
Thank you for the reply.  Here is the situation I am seeing so that you have all the details:

1. Open webpage containing deeplink and tap on link (image 1).
2. Link opens mobile safari and in the browser you see uber.com (image 2) followed by launch1.co (image 3) followed by a popup asking if you want to open the App store (image 4).
3a. Clicking cancel displays the screen in image 3.
3b. Clicking ok displays the Uber app in the app store with an Open button, indicating that the phone knows the app is already installed.
4. Clicking the OPEN IN THE UBER APP button from image 3 then displays a popup to Open in "Uber"? (image 5).
5. Opening in Uber now no longer shows the information contained in the deeplink once Uber opens, therefore rendering the deeplink useless.

I apologize if I'm missing something here that was already pointed out, but the only thing I could think of was to clear history and website data for Safari, which doesn't resolve the issue.  The links work fine on my other devices, so I'm not sure why it isn't working on this particular device.

Thanks,
Ken

Image 1: ![1](https://cloud.githubusercontent.com/assets/13436393/22555055/6980bbb2-e930-11e6-85cf-31d0f541e989.PNG)
Image 2: ![2](https://cloud.githubusercontent.com/assets/13436393/22555059/6985122a-e930-11e6-9b29-c17eaa00b6c0.PNG)
Image 3: ![3](https://cloud.githubusercontent.com/assets/13436393/22555054/697b3750-e930-11e6-970b-89852af94904.PNG)
Image 4: ![4](https://cloud.githubusercontent.com/assets/13436393/22555056/69841e4c-e930-11e6-9fa5-bb6c946e9d7a.PNG)
Image 5: ![5](https://cloud.githubusercontent.com/assets/13436393/22555057/6986234a-e930-11e6-965e-e43b4cc316e9.PNG)
Image 6: ![6](https://cloud.githubusercontent.com/assets/13436393/22555058/6986351a-e930-11e6-8830-61a3033409ba.PNG)
