### ISSUE TITLE
HTTPMethod got exposed in 0.8

### ISSUE THREAD

**Issue by wenxin3262** [uber/rides-ios-sdk#216]
Didn't have the issue before but after the upgrade, I am getting Ambiguous context error since Alamofire has its own `HTTPMethod` class.
I think UberSDK should mark `HTTPMethod` and related networking code as private classes.

**Comment by edjiang** [comment]
Thanks for the feedback. We marked it as public as part of the modularization effort in 0.8, since `UberRides` depends on `UberCore`.

Since it's not really intended to be consumed by the public, I think we can probably just namespace it for developer convenience.

In the meantime, you can use `Alamofire.HTTPMethod` and `UberCore.HTTPMethod` to distinguish between the classes.

**Comment by edjiang** [comment]
Fixed in 0.9!
