### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by sanjeev1994** [uber/rides-ios-sdk#219]
the server encountered an unexpected condition which prevented it from fulfilling the request

![simulator screen shot - iphone 6s - 2017-12-15 at 17 09 04](https://user-images.githubusercontent.com/7420699/34040814-74b9015e-e1bb-11e7-8c47-870cc81aa51a.png)

can someone let me know why I am getting this error

**Comment by edjiang** [comment]
Thanks for reporting this. I'll forward this to our backend team to have them take a look. What is your client_id, by the way?

**Comment by sanjeev1994** [comment]
Thanks for quick response,

My client ID:  0T4J6ew6R_e5O7vTCHuENTF8woy-EcEx

**Comment by keshavkishore09** [comment]
Hi edjiang,


I am facing the same issue while using Ride request Widget in my app.

**Comment by sanjeev1994** [comment]
Hi,
Is there any solution for this issue ???

**Comment by keshavkishore09** [comment]
Hi,

Even I waiting for the response and solution from Uber development team.

On Jan 3, 2018 4:53 PM, "sanjeev" <notifications@github.com> wrote:

Hi,
Is there any solution for this issue ???

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/uber/rides-ios-sdk/issues/219#issuecomment-354989683>,
or mute the thread

**Comment by edjiang** [comment]
Ride Request Widget was deprecated in 0.9, so I'm closing this as a non-issue anymore. Sorry!

https://github.com/uber/rides-ios-sdk/releases/tag/v0.9.0
