### ISSUE TITLE
Providing Custom Logic for LoginButton

### ISSUE THREAD

**Issue by aasatt** [uber/rides-ios-sdk#44]
I would like to be able to handle the OAuth on my own if the user does not have the Uber app installed. I have been able to achieve this with using the `LoginManager` directly with my own button. 

Here's is my logic for handling it: 

        let loginManager = LoginManager()
        loginManager.login(requestedScopes:[RidesScope.Request, RidesScope.AllTrips, RidesScope.Places], presentingViewController: self, completion: { accessToken, error in
            print("Token: \( accessToken?.tokenString)")
            print(error)
            if error != nil {
                uber.scopes = ["request", "all_trips", "places"]
                uber.authorize { (result) in
                    switch result {
                    case .Success(let token) :
                        print("Token: \(accessToken)")
                        self.token = accessToken
                        //handle successful login
                        break
                    case .Failure(let error) :
                        print(error)
                        //handle failed login
                        break
                    }
                }
            }
        })

A couple notes:
1. I have yet to get the login manager to login successfully. It says that my app is not authorized for the requested scopes but when it falls back on my own OAuth, with the same scopes, it works. 
2. How do I make the SDK aware of the login after I handle it myself?

**Comment by jbrophy17** [comment]
Hi @aasatt, the LoginButton is actually designed to work for exactly this case. You just need to add logic to your loginCompletion closure to handle both the Native and AuthorizationCode login types. If the login using Native fails, it will fallback to using AuthorizationCode. 

So, in your loginCompletion, you just need to check for an accessToken first (which will be there if Native succeeded). Otherwise, the completion will be called with no accessToken and no Error once the user has logged in on the AuthorizationCode grant login page. (which you code seems to be handling).

To do this, you will have to make use of the multiple `UberCallbackURIs` key in your .plist, for example:

```
<key>UberCallbackURIs</key>
<array>
    <dict>
        <key>UberCallbackURIType</key>
        <string>AuthorizationCode</string>
        <key>URIString</key>
        <string>https://myoauthserver.com/authorize</string>
    </dict>
    <dict>
        <key>UberCallbackURIType</key>
        <string>Native</string>
        <key>URIString</key>
        <string>sampleApp://native</string>
    </dict>
    <dict>
        <key>UberCallbackURIType</key>
        <string>General</string>
        <key>URIString</key>
        <string>http://someothercallback.com</string>
    </dict>
</array>
```

Which will tell the SDK which URIs to use for the different login types.

To address your notes:
1. That is strange, do you have the scopes you are requesting enabled on your developer dashboard? If you are signing in with the same account that is registered on the dashboard, you should be able get scopes that you aren't approved for yet (to allow testing). **However**, it looks like there is currently a problem with that functionality for privileged scopes obtained via Native login, which we are currently investigating.
2. You can save accessTokens manually using the `TokenManager.saveToken(accessToken:)` method. So once you get the access token string from your OAuth server, you can just call `TokenManager.saveToken("myAccessToken")` and the token will be saved and used for future requests

**Comment by jbrophy17** [comment]
see #45 regarding your first note

**Comment by aasatt** [comment]
@jbrophy17 Great. It does only seem to be an issue with the native login. This not working was definitely a source of confusion.  Thanks again for your help and for clearing things up. I think I have it working how I want it now.

**Comment by jbrophy17** [comment]
No problem, sorry for the confusion!
